vich_uploader:
    db_driver: orm
    metadata:
        type: attribute # 
                
   
    mappings:
        suite_image:
             uri_prefix: /assets/images/suite
             upload_destination: '%kernel.project_dir%/public/assets/images/suite'